### ISSUE TITLE
Unexpected namespaces

### ISSUE THREAD

**Issue by patridge** [WildernessLabs/Meadow.Contracts#145]
In the core Meadow API documentation, there are entries for two Meadow.Foundation namespaces.

![Wilderness Labs API docs namespace list showing two Meadow.Foundation namespaces.](https://github.com/WildernessLabs/Meadow.Contracts/assets/713665/32892bb4-6662-4435-a25c-cec0dc1e918f)

Doing a search for those two, you find two Meadow.Contracts files using that namespace that I'm guessing should be renamed to Meadow.Contracts instead.

* [Meadow.Foundation.Sensors.Camera](https://github.com/WildernessLabs/Meadow.Contracts/blob/develop/Source/Meadow.Contracts/Peripherals/Sensors/Camera/ICamera.cs#L4)
* [Meadow.Foundation.Sensors.Light](https://github.com/WildernessLabs/Meadow.Contracts/blob/develop/Source/Meadow.Contracts/Peripherals/Sensors/Light/ISolarIntensityGauge.cs)

**Comment by adrianstevens** [comment]
I'm on it

**Comment by patridge** [comment]
I believe this was resolved, but let me check. If so, and it isn't updated on the API docs, I would just need to run the build for that.

**Comment by patridge** [comment]
Not yet live on main/prod, but will be for the next deployment of Core.
